---
- hosts: all
  become: true

  tasks:
    - name: Shutdown only the ubuntu instances
      ansible.builtin.command: /sbin/shutdown -t now
      when:
       ansible_facts['os_family'] == "Debian"
